config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
    resources :likes, only: [:index, :create, :destroy]
  end

  authenticated :user do
    root 'topics#index', as: :authenticated_root
  end

  post :incoming, to: 'incoming#create'

  root 'welcome#index'

  get 'users/show'

  get 'welcome/contact'

  get 'likes/index'

  get 'welcome', to: 'welcome#index'

  get 'about', to: 'welcome#about'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :likes, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def created_bookmarks
    bookmarks.includes(:topic)
  end

  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include Pundit
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end
  
  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.topic = @topic
    @bookmark.user = current_user
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "Bookmark was saved successfully."
      redirect_to [@topic, @bookmark]
    else
      flash.now[:alert] = "failed to save bookmark"
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.update(bookmark_params)
      flash[:notice] = "Bookmark was successfully updated"
      redirect_to topic_bookmark_path
    else
      flash[:alert] = "Failed to update bookmark"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
      redirect_to @bookmark.topic
    else
      flash.now[:alert] = "failed to delete bookmark"
      render :show
    end
  end
  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment saved'
    else
      flash[:alert] = 'Comment creation failed'
    end
    redirect_to @topic
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!
  
  def create
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]


    @user = User.find_by_email(params[:sender])
    @topic = Topic.find_by_title(params[:subject])
    @url = params["body-plain"]


    # Check if user is nil, if so, create and save a new user
    if @user.nil?
      @user = User.new(
        email:                 params[:sender],
        password:              params[:sender],
        password_confirmation: params[:sender]
      )
      @user.save!
    end

     # Check if the topic is nil, if so, create and save a new topic
    if @topic.nil?
      @topic = @user.topics.build(title: params[:subject])
      @topic.save!
    end

     # Now that you're sure you have a valid user and topic, build and save a new bookmark
    @bookmark = @topic.bookmarks.build(url: @url)
    @bookmark.save
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like

    if @like.save
      flash[:notice] = "Bookmark liked"
      redirect_to [@bookmark]
    else
      flash.now[:alert] = "Failed to like Bookmark"
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find_by(bookmark: @bookmark)

    if @like.destroy
      flash[:notice] = "Bookmark unliked"
      redirect_to [@bookmark]
    else
      flash[:alert] = "Failed to unlike Bookmark"
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to root_path, notice: 'Topic saved'
    else
      flash[:alert] = 'Topic not saved'
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      flash[:notice] = "Topic was updated succcessfully"
      redirect_to @topic
    else
      flash[:alert] = "Failed to update topic"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "Failed to delete post."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(email)
    image_tag("https://robohash.org/#{email}.png?size=128x128")
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def user_is_authorized_to_edit_bookmarks?
    policy(@bookmark).edit?
  end

  def user_is_authorized_to_destroy_bookmarks?
    policy(@bookmark).destroy?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<div class="col-md-8">
  <%= form_for [@bookmark.topic, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Bookmark URL" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

  <%= form_for [@topic, @bookmark] do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.submit "Save" %>
    <% end %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.url %></h1>

<div class="col-md-4">
  <div style="text-align:center">
    <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
      <% if user_is_authorized_to_edit_bookmarks? %>
        <%= link_to "Edit", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: 'btn btn-success' %>
      <% end %>
      <% if user_is_authorized_to_destroy_bookmarks? %>
        <%= link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Do you want to delete this bookmark?'} %>
      <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<h1>Add comment</h1>
<%= form_for [@topic, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
<div>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; like
    <% end %>
  <% end %>
</div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1 class="text-center">Topics</h1>

<%= link_to 'New Topic', new_topic_path, class: 'btn btn-primary' %>
<% @topics.each do |topic| %>
  <div class="topic">
    <%= link_to topic.title, topic_path(topic) %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>New Topics</h1>

<%= form_for @topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Save" %>
  <% end %>

app/views/topics/show.html.erb
<h1 class="text-center"><%= @topic.title %></h1>

  <%= link_to "Edit Topic", edit_topic_path(@topic), class: 'btn btn-success' %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'} %>

  <div class="col-md-0">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-primary'%>
  </div>

 <div class="col-md-10">
   <% @topic.bookmarks.each do |bookmark, url| %>
    <div class="media">
      <div class="media-heading">
        <h4><%= link_to bookmark.url, topic_bookmark_path(@topic, bookmark) %></h4>
      </div>
    </div>
    <% end %>
  </div>


</div>

app/views/users/show.html.erb
<br>
<div class="container">
  <div class="row">
    <h3>My Blocmarks</h3>
      <div class="col-md-8">
        <% @user_bookmarks.each do |bookmark| %>
            <h4 class="media-heading">
              <%="##{bookmark.topic.title}" %>
              <br>
              <%= link_to bookmark.url, topic_bookmark_path(topic_url, bookmark), :target => '_self' %> <%= link_to "Delete", [bookmark.topic, bookmark], method: :delete, class: 'btn btn-danger' %>
              <br>
            </h4>
        <% end %>
      </div>
  </div>
</div>
    <br>
<div class="container">
  <div class="row">
    <h3>Liked Bookmarks:</h3>
      <div class="col-md-8">
        <% @liked_bookmarks.each do |bookmark| %>
          <h4 class="media-heading">
            <%="##{bookmark.topic.title}" %>
            <br>
            <%= link_to bookmark.url, topic_bookmark_path(topic_url, bookmark), :target => '_self' %> <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
            <br>
          </h4>
        <% end %>
      </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>about</h1>
<p>In cooperation with Bloc.io</p>

app/views/welcome/contact.html.erb
<div class="container">
  <div class="row">
    <div class="contact">
        <p>Please Feel Free to Leave a Feedback to Improve This Project.</p>
      <form>
      <div class="form-group">
        <div class="col-md-4">
          <h4>Name</h4>
            <input id="Name" placeholder="Please Write Your Name Here" type="text"></input>
        </div>
        <div class="col-md-4">
          <h4>Email Address</h4>
            <input id="Email" placeholder="Please Write Your Email Here" type="text"></input>
        </div>
        <div class="col-lg-10">
          <h4>Feedback</h4>
            <textarea rows="4"></textarea>
            <button class="radius button" type="submit">Submit</button>
        </div>
      </div>
    </form>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<br>
  <div class="jumbotron">
    <h1>BlocMarks</h1>
    <p>Spark your bookmark here!</p>
      <p>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-primary'  %> or
        <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-primary'  %> to Access
      </p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2 id="headline">Organize Your Bookmarks with Style</h2>
    </div>
  </div>

  <div class="header">
    <div class="col-lg-12">
      <div class="container">
        <div class="col-md-4">
          <h4>Best code school out there</h4>
          <a class="embedly-card" href="http://www.bloc.io">Bloc | Online Coding Bootcamp for Developers and Web Designers</a>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </div>
        <div class="col-md-4">
          <h4>Need help with code?</h4>
          <a class="embedly-card" href="http://www.stackoverflow.com">Stack Overflow</a>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </div>
        <div class="col-md-4">
          <h4>Need instructions with your code?</h4>
          <a class="embedly-card" href="http://www.youtube.com">YouTube</a>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </div>
      </div>
    </div>
  </div>

  