config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
    resources :likes, only: [:index, :create, :destroy]
  end

  authenticated :user do
    root 'topics#index', as: :authenticated_root
  end

  post :incoming, to: 'incoming#create'

  root 'welcome#index'

  get 'users/show'

  get 'welcome/contact'

  get 'likes/index'

  get 'welcome', to: 'welcome#index'

  get 'about', to: 'welcome#about'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :likes, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def created_bookmarks
    bookmarks.includes(:topic)
  end

  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end
  
  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.topic = @topic
    @bookmark.user = current_user
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "Bookmark was saved successfully."
      redirect_to [@topic, @bookmark]
    else
      flash.now[:alert] = "failed to save bookmark"
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.update(bookmark_params)
      flash[:notice] = "Bookmark was successfully updated"
      redirect_to topic_bookmark_path
    else
      flash[:alert] = "Failed to update bookmark"
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
      redirect_to @bookmark.topic
    else
      flash.now[:alert] = "failed to delete bookmark"
      render :show
    end
  end
  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment saved'
    else
      flash[:alert] = 'Comment creation failed'
    end
    redirect_to @topic
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!
  
  def create
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]


    @user = User.find_by_email(params[:sender])
    @topic = Topic.find_by_title(params[:subject])
    @url = params["body-plain"]


    # Check if user is nil, if so, create and save a new user
    if @user.nil?
      @user = User.new(
        email:                 params[:sender],
        password:              params[:sender],
        password_confirmation: params[:sender]
      )
      @user.save!
    end

     # Check if the topic is nil, if so, create and save a new topic
    if @topic.nil?
      @topic = @user.topics.build(title: params[:subject])
      @topic.save!
    end

     # Now that you're sure you have a valid user and topic, build and save a new bookmark
    @bookmark = @topic.bookmarks.build(url: @url)
    @bookmark.save
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like

    if @like.save
      flash[:notice] = "Bookmark liked"
      redirect_to [@bookmark]
    else
      flash.now[:alert] = "Failed to like Bookmark"
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find_by(bookmark: @bookmark)

    if @like.destroy
      flash[:notice] = "Bookmark unliked"
      redirect_to [@bookmark]
    else
      flash[:alert] = "Failed to unlike Bookmark"
      render :show
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to root_path, notice: 'Topic saved'
    else
      flash[:alert] = 'Topic not saved'
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      flash[:notice] = "Topic was updated succcessfully"
      redirect_to @topic
    else
      flash[:alert] = "Failed to update topic"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "Failed to delete post."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(email)
    image_tag("https://robohash.org/#{email}.png?size=128x128")
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def user_is_authorized_to_edit_bookmarks?
    policy(@bookmark).edit?
  end

  def user_is_authorized_to_destroy_bookmarks?
    policy(@bookmark).destroy?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="col-sm-12">
      <p class="footmess"> More Options Here </p>
      <%= link_to "Sign Up", new_user_registration_path %> •
      <%= link_to "Sign In", new_user_session_path %> •
      <%= link_to "About", about_path %> •
      <%= link_to "Contact Me", welcome_contact_path %> •
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Blocmarks", welcome_path %></li>
    <li><%= link_to "My Profile", users_show_path %></li>
    <li><%= link_to "Topics", topics_path %></li>
    
    <div class="pull-right user-info">
      <% if user_signed_in? %>
        <strong><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></strong> |
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <%= yield %>

</div>
</body>

</html>